"""添加物品属性变更记录表

Revision ID: 9571161d4354
Revises: c7b4ae0a0411
Create Date: 2026-04-09 20:19:01.514366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9571161d4354'
down_revision: Union[str, None] = 'c7b4ae0a0411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_attribute_changes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('attribute_name', sa.String(length=50), nullable=False, comment='变更的属性名'),
    sa.Column('attribute_label', sa.String(length=100), nullable=True, comment='属性显示名称'),
    sa.Column('value_before', sa.Text(), nullable=True, comment='变更前值（JSON或文本）'),
    sa.Column('value_after', sa.Text(), nullable=True, comment='变更后值（JSON或文本）'),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('change_type', sa.String(length=30), nullable=True, comment='变更类型: update/enhance/degrade/acquire/lose'),
    sa.Column('trigger_event', sa.Text(), nullable=True, comment='触发事件'),
    sa.Column('description', sa.Text(), nullable=True, comment='变更描述'),
    sa.Column('involved_character_id', sa.String(length=36), nullable=True),
    sa.Column('involved_character_name', sa.String(length=100), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True, comment='额外数据（如对比详情、原因等）'),
    sa.Column('source_type', sa.String(length=20), nullable=True, comment='来源: story/analysis/manual'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['involved_character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_attribute_changes_item_id'), 'item_attribute_changes', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_attribute_changes_project_id'), 'item_attribute_changes', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_attribute_changes_project_id'), table_name='item_attribute_changes')
    op.drop_index(op.f('ix_item_attribute_changes_item_id'), table_name='item_attribute_changes')
    op.drop_table('item_attribute_changes')
    # ### end Alembic commands ###