"""添加物品管理表

Revision ID: c7b4ae0a0411
Revises: add_attribute_system
Create Date: 2026-04-09 11:39:52.779472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7b4ae0a0411'
down_revision: Union[str, None] = 'add_attribute_system'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='分类名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='分类描述'),
    sa.Column('parent_id', sa.String(length=36), nullable=True, comment='父分类ID'),
    sa.Column('level', sa.Integer(), nullable=True, comment='层级（1为顶级分类）'),
    sa.Column('path', sa.String(length=500), nullable=True, comment='分类路径（如：法宝,攻击类法宝,剑类法宝）'),
    sa.Column('order_index', sa.Integer(), nullable=True, comment='同级排序'),
    sa.Column('attribute_template', sa.Text(), nullable=True, comment='该分类下物品的属性模板'),
    sa.Column('default_unit', sa.String(length=20), nullable=True, comment='默认计量单位'),
    sa.Column('default_rarity', sa.String(length=20), nullable=True, comment='默认稀有度'),
    sa.Column('genre_type', sa.String(length=50), nullable=True, comment='适用题材类型: fantasy/modern/scifi/historical/common'),
    sa.Column('item_count', sa.Integer(), nullable=True, comment='该分类下物品数量（含子分类）'),
    sa.Column('is_system', sa.Boolean(), nullable=True, comment='是否系统预设分类'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['item_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_categories_project_id'), 'item_categories', ['project_id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='物品名称'),
    sa.Column('alias', sa.JSON(), nullable=True, comment="别名/曾用名列表: ['玄铁重剑', '那把剑']"),
    sa.Column('category_id', sa.String(length=36), nullable=True, comment='分类ID'),
    sa.Column('description', sa.Text(), nullable=True, comment='物品描述/外观'),
    sa.Column('unit', sa.String(length=20), nullable=True, comment='计量单位'),
    sa.Column('quantity', sa.Float(), nullable=True, comment='当前数量（支持小数，如灵石100.5）'),
    sa.Column('initial_quantity', sa.Float(), nullable=True, comment='初始数量（用于重置参考）'),
    sa.Column('max_quantity', sa.Float(), nullable=True, comment='最大堆叠数量（可选）'),
    sa.Column('rarity', sa.String(length=20), nullable=True, comment='稀有度: common/uncommon/rare/epic/legendary/artifact'),
    sa.Column('quality', sa.String(length=50), nullable=True, comment='品质（如：上品、极品）'),
    sa.Column('attributes', sa.JSON(), nullable=True, comment='物品属性(JSON): {attack: 100, defense: 50}'),
    sa.Column('special_effects', sa.Text(), nullable=True, comment='特殊效果描述'),
    sa.Column('lore', sa.Text(), nullable=True, comment='物品传说/背景故事'),
    sa.Column('value', sa.Integer(), nullable=True, comment='价值（游戏币/灵石等）'),
    sa.Column('source_type', sa.String(length=20), nullable=True, comment='来源: story(剧情)/craft(制作)/purchase(购买)/drop(掉落)'),
    sa.Column('source_chapter_id', sa.String(length=36), nullable=True, comment='首次出现章节ID'),
    sa.Column('source_chapter_number', sa.Integer(), nullable=True, comment='首次出现章节号'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='物品状态'),
    sa.Column('status_changed_at', sa.DateTime(), nullable=True, comment='状态最后变更时间'),
    sa.Column('owner_character_id', sa.String(length=36), nullable=True, comment='当前持有者ID'),
    sa.Column('owner_character_name', sa.String(length=100), nullable=True, comment='当前持有者名称（冗余存储）'),
    sa.Column('related_characters', sa.JSON(), nullable=True, comment='关联角色名列表（非持有者的相关角色）'),
    sa.Column('related_chapters', sa.JSON(), nullable=True, comment='关联章节号列表'),
    sa.Column('tags', sa.JSON(), nullable=True, comment="标签列表: ['法宝', '传承', '神秘']"),
    sa.Column('notes', sa.Text(), nullable=True, comment='创作备注'),
    sa.Column('is_plot_critical', sa.Boolean(), nullable=True, comment='是否剧情关键物品'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['category_id'], ['item_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_item_category', 'items', ['category_id'], unique=False)
    op.create_index('idx_item_owner', 'items', ['owner_character_id'], unique=False)
    op.create_index('idx_item_project_status', 'items', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_items_project_id'), 'items', ['project_id'], unique=False)
    op.create_index(op.f('ix_items_status'), 'items', ['status'], unique=False)
    op.create_table('item_quantity_changes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=False, comment='变更类型'),
    sa.Column('quantity_before', sa.Float(), nullable=True, comment='变更前数量'),
    sa.Column('quantity_change', sa.Float(), nullable=False, comment='变更量（正数增加，负数减少）'),
    sa.Column('quantity_after', sa.Float(), nullable=True, comment='变更后数量'),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True, comment='变更原因'),
    sa.Column('description', sa.Text(), nullable=True, comment='详细描述'),
    sa.Column('involved_character_id', sa.String(length=36), nullable=True),
    sa.Column('involved_character_name', sa.String(length=100), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True, comment='关联实体类型(如：任务、交易等)'),
    sa.Column('related_entity_id', sa.String(length=36), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True, comment='来源: story/analysis/manual'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['involved_character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_quantity_changes_item_id'), 'item_quantity_changes', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_quantity_changes_project_id'), 'item_quantity_changes', ['project_id'], unique=False)
    op.create_table('item_status_changes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('status_before', sa.String(length=20), nullable=True, comment='变更前状态'),
    sa.Column('status_after', sa.String(length=20), nullable=False, comment='变更后状态'),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('trigger_event', sa.Text(), nullable=True, comment='触发事件'),
    sa.Column('description', sa.Text(), nullable=True, comment='变更描述'),
    sa.Column('involved_character_id', sa.String(length=36), nullable=True),
    sa.Column('involved_character_name', sa.String(length=100), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True, comment='来源: story/analysis/manual'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['involved_character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_status_changes_item_id'), 'item_status_changes', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_status_changes_project_id'), 'item_status_changes', ['project_id'], unique=False)
    op.create_table('item_transfers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('transfer_type', sa.String(length=20), nullable=False, comment='流转类型'),
    sa.Column('from_character_id', sa.String(length=36), nullable=True, comment='转出角色ID'),
    sa.Column('from_character_name', sa.String(length=100), nullable=True, comment='转出角色名称'),
    sa.Column('to_character_id', sa.String(length=36), nullable=True, comment='转入角色ID'),
    sa.Column('to_character_name', sa.String(length=100), nullable=True, comment='转入角色名称'),
    sa.Column('chapter_id', sa.String(length=36), nullable=True, comment='发生章节ID'),
    sa.Column('chapter_number', sa.Integer(), nullable=True, comment='发生章节号'),
    sa.Column('location', sa.String(length=200), nullable=True, comment='发生地点'),
    sa.Column('quantity', sa.Float(), nullable=True, comment='流转数量'),
    sa.Column('quantity_after', sa.Float(), nullable=True, comment='流转后物品总数量'),
    sa.Column('description', sa.Text(), nullable=True, comment='流转描述'),
    sa.Column('reason', sa.Text(), nullable=True, comment='流转原因'),
    sa.Column('conditions', sa.Text(), nullable=True, comment='流转条件（如：交易价格、代价等）'),
    sa.Column('quote_text', sa.Text(), nullable=True, comment='原文引用'),
    sa.Column('quote_position', sa.Integer(), nullable=True, comment='引用位置'),
    sa.Column('source_type', sa.String(length=20), nullable=True, comment='来源: story/analysis/manual'),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='发生时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_transfers_item_id'), 'item_transfers', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_transfers_project_id'), 'item_transfers', ['project_id'], unique=False)
    op.alter_column('career_templates', 'type',
               existing_type=sa.VARCHAR(length=20),
               comment='职业类型: main(主职业)/sub(副职业)',
               existing_comment='职业类型: main/sub',
               existing_nullable=False)
    op.alter_column('career_templates', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment='职业分类（如：战斗系、生产系、辅助系）',
               existing_comment='职业分类',
               existing_nullable=True)
    op.alter_column('career_templates', 'applicable_genres',
               existing_type=sa.TEXT(),
               comment="适用小说类型(JSON): ['玄幻', '仙侠']",
               existing_comment='适用小说类型(JSON)',
               existing_nullable=False)
    op.alter_column('career_templates', 'stages',
               existing_type=sa.TEXT(),
               comment="职业阶段列表(JSON): [{level:1, name:'', description:''}, ...]",
               existing_comment='职业阶段列表(JSON)',
               existing_nullable=False)
    op.alter_column('career_templates', 'max_stage',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_comment='最大阶段数',
               existing_nullable=False)
    op.alter_column('career_templates', 'requirements',
               existing_type=sa.TEXT(),
               comment='职业要求/限制',
               existing_comment='职业要求',
               existing_nullable=True)
    op.alter_column('career_templates', 'special_abilities',
               existing_type=sa.TEXT(),
               comment='特殊能力描述',
               existing_comment='特殊能力',
               existing_nullable=True)
    op.alter_column('career_templates', 'attribute_bonuses',
               existing_type=sa.TEXT(),
               comment="属性加成(JSON): {strength: '+10%', intelligence: '+5%'}",
               existing_comment='属性加成(JSON)',
               existing_nullable=True)
    op.alter_column('career_templates', 'base_attributes',
               existing_type=sa.TEXT(),
               comment='职业基础能力配置(JSON): {灵力: 60, 悟性: 70}',
               existing_comment='基础能力配置(JSON)',
               existing_nullable=True)
    op.alter_column('career_templates', 'per_stage_bonus',
               existing_type=sa.TEXT(),
               comment='每阶段能力加成(JSON): {灵力: {per_stage: 50}, 悟性: {per_stage: 5}}',
               existing_comment='每阶段能力加成(JSON)',
               existing_nullable=True)
    op.alter_column('career_templates', 'is_official',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='是否为官方预置模板',
               existing_comment='是否官方模板',
               existing_nullable=True)
    op.alter_column('career_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='是否启用',
               existing_nullable=True)
    op.alter_column('career_templates', 'order_index',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_comment='排序序号',
               existing_nullable=True)
    op.alter_column('careers', 'base_attributes',
               existing_type=sa.TEXT(),
               comment='职业基础能力配置(JSON): {灵力: 60, 悟性: 70}',
               existing_comment='职业基础能力配置(JSON)',
               existing_nullable=True)
    op.alter_column('careers', 'per_stage_bonus',
               existing_type=sa.TEXT(),
               comment='每阶段能力加成(JSON): {灵力: {per_stage: 50}, 悟性: {per_stage: 5}}',
               existing_comment='每阶段能力加成(JSON)',
               existing_nullable=True)
    op.alter_column('characters', 'attributes',
               existing_type=sa.TEXT(),
               comment='角色能力数值(JSON): {境界: {type:stage, value:3, name:金丹}, 灵力: {type:numeric, value:850}}',
               existing_comment='角色能力数值(JSON)',
               existing_nullable=True)
    op.alter_column('characters', 'base_attributes',
               existing_type=sa.TEXT(),
               comment='初始能力值(JSON)，用于重置参考',
               existing_comment='初始能力值(JSON)',
               existing_nullable=True)
    op.alter_column('settings', 'smtp_host',
               existing_type=sa.VARCHAR(length=200),
               comment='SMTP服务器地址',
               existing_nullable=True)
    op.alter_column('settings', 'smtp_port',
               existing_type=sa.INTEGER(),
               comment='SMTP端口',
               existing_nullable=True)
    op.alter_column('settings', 'smtp_username',
               existing_type=sa.VARCHAR(length=200),
               comment='SMTP用户名',
               existing_nullable=True)
    op.alter_column('settings', 'smtp_password',
               existing_type=sa.VARCHAR(length=200),
               comment='SMTP密码',
               existing_nullable=True)
    op.alter_column('settings', 'smtp_use_tls',
               existing_type=sa.INTEGER(),
               comment='是否使用TLS',
               existing_nullable=True)
    op.alter_column('settings', 'smtp_use_ssl',
               existing_type=sa.INTEGER(),
               comment='是否使用SSL',
               existing_nullable=True)
    op.alter_column('settings', 'smtp_from_email',
               existing_type=sa.VARCHAR(length=200),
               comment='发件人邮箱',
               existing_nullable=True)
    op.alter_column('settings', 'smtp_from_name',
               existing_type=sa.VARCHAR(length=100),
               comment='发件人名称',
               existing_nullable=True)
    op.alter_column('settings', 'email_auth_enabled',
               existing_type=sa.INTEGER(),
               comment='是否启用邮箱认证',
               existing_nullable=True)
    op.alter_column('settings', 'email_register_enabled',
               existing_type=sa.INTEGER(),
               comment='是否启用邮箱注册',
               existing_nullable=True)
    op.alter_column('settings', 'verification_code_ttl_minutes',
               existing_type=sa.INTEGER(),
               comment='验证码有效期(分钟)',
               existing_nullable=True)
    op.alter_column('settings', 'verification_resend_interval_seconds',
               existing_type=sa.INTEGER(),
               comment='验证码重发间隔(秒)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settings', 'verification_resend_interval_seconds',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='验证码重发间隔(秒)',
               existing_nullable=True)
    op.alter_column('settings', 'verification_code_ttl_minutes',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='验证码有效期(分钟)',
               existing_nullable=True)
    op.alter_column('settings', 'email_register_enabled',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='是否启用邮箱注册',
               existing_nullable=True)
    op.alter_column('settings', 'email_auth_enabled',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='是否启用邮箱认证',
               existing_nullable=True)
    op.alter_column('settings', 'smtp_from_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='发件人名称',
               existing_nullable=True)
    op.alter_column('settings', 'smtp_from_email',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='发件人邮箱',
               existing_nullable=True)
    op.alter_column('settings', 'smtp_use_ssl',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='是否使用SSL',
               existing_nullable=True)
    op.alter_column('settings', 'smtp_use_tls',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='是否使用TLS',
               existing_nullable=True)
    op.alter_column('settings', 'smtp_password',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='SMTP密码',
               existing_nullable=True)
    op.alter_column('settings', 'smtp_username',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='SMTP用户名',
               existing_nullable=True)
    op.alter_column('settings', 'smtp_port',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='SMTP端口',
               existing_nullable=True)
    op.alter_column('settings', 'smtp_host',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='SMTP服务器地址',
               existing_nullable=True)
    op.alter_column('characters', 'base_attributes',
               existing_type=sa.TEXT(),
               comment='初始能力值(JSON)',
               existing_comment='初始能力值(JSON)，用于重置参考',
               existing_nullable=True)
    op.alter_column('characters', 'attributes',
               existing_type=sa.TEXT(),
               comment='角色能力数值(JSON)',
               existing_comment='角色能力数值(JSON): {境界: {type:stage, value:3, name:金丹}, 灵力: {type:numeric, value:850}}',
               existing_nullable=True)
    op.alter_column('careers', 'per_stage_bonus',
               existing_type=sa.TEXT(),
               comment='每阶段能力加成(JSON)',
               existing_comment='每阶段能力加成(JSON): {灵力: {per_stage: 50}, 悟性: {per_stage: 5}}',
               existing_nullable=True)
    op.alter_column('careers', 'base_attributes',
               existing_type=sa.TEXT(),
               comment='职业基础能力配置(JSON)',
               existing_comment='职业基础能力配置(JSON): {灵力: 60, 悟性: 70}',
               existing_nullable=True)
    op.alter_column('career_templates', 'order_index',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_comment='排序序号',
               existing_nullable=True)
    op.alter_column('career_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_comment='是否启用',
               existing_nullable=True)
    op.alter_column('career_templates', 'is_official',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               comment='是否官方模板',
               existing_comment='是否为官方预置模板',
               existing_nullable=True)
    op.alter_column('career_templates', 'per_stage_bonus',
               existing_type=sa.TEXT(),
               comment='每阶段能力加成(JSON)',
               existing_comment='每阶段能力加成(JSON): {灵力: {per_stage: 50}, 悟性: {per_stage: 5}}',
               existing_nullable=True)
    op.alter_column('career_templates', 'base_attributes',
               existing_type=sa.TEXT(),
               comment='基础能力配置(JSON)',
               existing_comment='职业基础能力配置(JSON): {灵力: 60, 悟性: 70}',
               existing_nullable=True)
    op.alter_column('career_templates', 'attribute_bonuses',
               existing_type=sa.TEXT(),
               comment='属性加成(JSON)',
               existing_comment="属性加成(JSON): {strength: '+10%', intelligence: '+5%'}",
               existing_nullable=True)
    op.alter_column('career_templates', 'special_abilities',
               existing_type=sa.TEXT(),
               comment='特殊能力',
               existing_comment='特殊能力描述',
               existing_nullable=True)
    op.alter_column('career_templates', 'requirements',
               existing_type=sa.TEXT(),
               comment='职业要求',
               existing_comment='职业要求/限制',
               existing_nullable=True)
    op.alter_column('career_templates', 'max_stage',
               existing_type=sa.INTEGER(),
               server_default=sa.text('10'),
               existing_comment='最大阶段数',
               existing_nullable=False)
    op.alter_column('career_templates', 'stages',
               existing_type=sa.TEXT(),
               comment='职业阶段列表(JSON)',
               existing_comment="职业阶段列表(JSON): [{level:1, name:'', description:''}, ...]",
               existing_nullable=False)
    op.alter_column('career_templates', 'applicable_genres',
               existing_type=sa.TEXT(),
               comment='适用小说类型(JSON)',
               existing_comment="适用小说类型(JSON): ['玄幻', '仙侠']",
               existing_nullable=False)
    op.alter_column('career_templates', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment='职业分类',
               existing_comment='职业分类（如：战斗系、生产系、辅助系）',
               existing_nullable=True)
    op.alter_column('career_templates', 'type',
               existing_type=sa.VARCHAR(length=20),
               comment='职业类型: main/sub',
               existing_comment='职业类型: main(主职业)/sub(副职业)',
               existing_nullable=False)
    op.drop_index(op.f('ix_item_transfers_project_id'), table_name='item_transfers')
    op.drop_index(op.f('ix_item_transfers_item_id'), table_name='item_transfers')
    op.drop_table('item_transfers')
    op.drop_index(op.f('ix_item_status_changes_project_id'), table_name='item_status_changes')
    op.drop_index(op.f('ix_item_status_changes_item_id'), table_name='item_status_changes')
    op.drop_table('item_status_changes')
    op.drop_index(op.f('ix_item_quantity_changes_project_id'), table_name='item_quantity_changes')
    op.drop_index(op.f('ix_item_quantity_changes_item_id'), table_name='item_quantity_changes')
    op.drop_table('item_quantity_changes')
    op.drop_index(op.f('ix_items_status'), table_name='items')
    op.drop_index(op.f('ix_items_project_id'), table_name='items')
    op.drop_index('idx_item_project_status', table_name='items')
    op.drop_index('idx_item_owner', table_name='items')
    op.drop_index('idx_item_category', table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_item_categories_project_id'), table_name='item_categories')
    op.drop_table('item_categories')
    # ### end Alembic commands ###